[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vulpin"
version = "0.9"
description = "Vulpin programming language"
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.8"
authors = [
    {name = "vulpin-lang"}
]
keywords = ["programming-language", "interpreter", "scripting", "minimal", "vulpin"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Other Scripting Engines",
    "Topic :: Software Development :: Interpreters",
    "Topic :: Software Development :: Compilers",
]

[project.urls]
Homepage = "https://github.com/vulpin-lang/Vulpin"
Repository = "https://github.com/vulpin-lang/Vulpin"
Issues = "https://github.com/vulpin-lang/Vulpin/issues"

[project.optional-dependencies]
gui = ["customtkinter"]
dev = [
    "pytest",
    "black",
    "flake8",
]

[tool.setuptools]
packages = []
include-package-data = true

