#include<stdio.h>
#include<stdlib.h>
#include<ctype.h>
#include<string.h>
typedef enum{PRINT,PNL,CLASS,SREP,DELAY,INPUT,EXEC,QUIT,ERR,IMPORT,FUNC,RET,TRY,CATCH,ENDTRY,SWITCH,CASE,DEF,ENDSW,LABEL,JUMP,FOR,CEXEC,ASSIGN,IF,ELSE,ENDIF,WHILE,WEND,ENDFN,PLUS,MINUS,MUL,DIV,NUM,STR,ID,EOF_T,UNK}TT;
typedef struct{TT t;char v[256];}Tk;
Tk mk(TT t,const char*v){Tk k;k.t=t;strncpy(k.v,v,255);k.v[255]=0;return k;}
int ic(char c){return strchr("GPSDKXEUQFRTCYWVNZLJOAC",c)!=NULL;}
Tk nx(const char**s){while(**s==' '||**s=='\t'||**s=='\n'||**s=='\r')(*s)++;if(!**s)return mk(EOF_T,"EOF");char c=**s;if(c=='#'){while(**s!='\n'&&**s)(*s)++;return nx(s);}if(c=='"'){(*s)++;char b[256];int i=0;while(**s!='"'&&**s&&i<255)b[i++]=*(*s)++;if(**s=='"')(*s)++;b[i]=0;return mk(STR,b);}if(isdigit(c)){char b[64];int i=0;while((isdigit(**s)||**s=='.')&&i<63)b[i++]=*(*s)++;b[i]=0;return mk(NUM,b);}if(isupper(c)&&ic(c)){(*s)++;char d[2]={c,0};switch(c){case'G':return mk(PRINT,d);case'P':return mk(PNL,d);case'A':return mk(CLASS,d);case'S':return mk(SREP,d);case'D':return mk(DELAY,d);case'K':return mk(INPUT,d);case'X':return mk(EXEC,d);case'Q':return mk(QUIT,d);case'E':return mk(ERR,d);case'U':return mk(IMPORT,d);case'F':return mk(FUNC,d);case'R':return mk(RET,d);case'T':return mk(TRY,d);case'C':return mk(CATCH,d);case'Y':return mk(ENDTRY,d);case'W':return mk(SWITCH,d);case'V':return mk(CASE,d);case'N':return mk(DEF,d);case'Z':return mk(ENDSW,d);case'L':return mk(LABEL,d);case'J':return mk(JUMP,d);case'O':return mk(FOR,d);}}if(isalpha(c)||c=='_'){char b[256];int i=0;while((isalnum(**s)||**s=='_')&&i<255)b[i++]=*(*s)++;b[i]=0;return mk(ID,b);}(*s)++;if((c=='<'||c=='>')&&**s=='='){char op[3]={c,'=',0};(*s)++;return mk(UNK,op);}switch(c){case'=':return mk(ASSIGN,"=");case'?':return mk(IF,"?");case':':return mk(ELSE,":");case';':return mk(ENDIF,";");case'@':return mk(WHILE,"@");case'&':return mk(WEND,"&");case'~':return mk(ENDFN,"~");case'!':return mk(CEXEC,"!");case'+':return mk(PLUS,"+");case'-':return mk(MINUS,"-");case'*':return mk(MUL,"*");case'/':return mk(DIV,"/");}return mk(UNK,&c);}
